version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm run cy:verify
      
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
     
      - run: npm run tags TAGS='@olx'; npm run report

      - store_artifacts:
          path: /root/project/cypress/videos
          destination: videos

      - store_artifacts:
          path: /root/project/report    
          destination: report
                
      - store_artifacts:
          path: /root/project/mochawesome-report
          destination: mochawesome


workflows:
  version: 2
  build:
    jobs:
      - test